import matplotlib.pyplot as plt
import logging
import os
import pandas as pd

logger = logging.getLogger("TimeSeriesForecaster")


def plot_forecast(series, forecast, horizon, output_dir="shared/outputs"):
    """
    Plot the original time series along with the forecasted values.

    The plot displays:
    - the historical series (blue)
    - the predicted future values based on ARIMA + GARCH (red)

    Parameters
    ----------
    series : pandas.Series
        Historical time series indexed by date.
    forecast : array-like
        Forecasted numerical values generated by ARIMA.
    horizon : int
        Number of forecasted points to display.
    output_dir : str, optional
        Directory where the forecast figure will be saved
        (default is "shared/outputs").

    Returns
    -------
    None
        Saves the Matplotlib figure to disk instead of displaying it.

    Notes
    -----
    Logging Levels:
        - INFO: indicates that the forecast plot is being generated and saved
        - DEBUG: confirms the successful save operation

    Examples
    --------
    >>> plot_forecast(series, forecast, 20)
    Saves the forecast figure in the shared outputs directory.
    """
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    logger.info("Generating forecast plot")

    # Create the figure
    plt.figure(figsize=(10, 5))
    plt.plot(series, label="Original")
    plt.plot(
        range(len(series), len(series) + horizon),
        forecast,
        label="Forecast",
        color="red"
    )
    plt.legend()
    plt.title("ARIMA + GARCH Forecast")

    # Save figure to disk (Docker-friendly)
    output_path = os.path.join(output_dir, "forecast.png")
    plt.savefig(output_path)
    plt.close()

    logger.info(f"Forecast plot saved to {output_path}")
    logger.debug("Forecast plot generation completed successfully")


# --------------------------------------------------
# Entry point for Docker multi-container execution
# --------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )

    logger.info("Starting visualization step")

    # Load processed data
    series = pd.read_csv(
        "shared/processed/cleaned_series.csv",
        index_col=0,
        parse_dates=True
    ).iloc[:, 0]

    forecast = pd.read_csv(
        "shared/outputs/forecast.csv"
    )["forecast"]

    plot_forecast(series, forecast, horizon=len(forecast))

    logger.info("Visualization completed successfully")
